window.gifts = [
  // === SETUP / ESCRITORIO ======================================
  {
    id: "UTESPELARE-STYRSPEL_Escritorio_y_silla_p/gamer_negro/gris",
    name: "Escritorio y silla gamer negro/gris UTESPELARE",
    category: "setup",
    image:
      "https://www.ikea.com/mx/es/images/products/utespelare-styrspel-escritorio-y-silla-p-gamer-negro-gris__1123700_pe874860_s5.jpg?f=xl",
    tags: ["Muebles"],
    search: "Escritorio y silla gamer negro/gris UTESPELARE",
    storeUrl:
      "https://www.ikea.com/mx/es/p/utespelare-styrspel-escritorio-y-silla-p-gamer-negro-gris-s49491167",
    storeLabel: "Ver en IKEA",
    priority: true,
  },
  {
    id: "SAMBORD-Lámpara-de-escritorio-negro/blanco",
    name: "Lámpara de escritorio negro/blanco SAMBORD",
    category: "setup",
    image:
      "https://www.ikea.com/mx/es/images/products/sambord-lampara-de-escritorio-negro-blanco__1375676_pe960327_s5.jpg?f=xl",
    tags: ["Tecnología", "Accesorios"],
    search: "Lámpara de escritorio SAMBORD",
    storeUrl:
      "https://www.ikea.com/mx/es/p/sambord-lampara-de-escritorio-negro-blanco-10586958",
    storeLabel: "Ver en IKEA",
    priority: true,
    purchased: true,
  },
  {
    id: "multicontacto-escritorio",
    name: "Multicontacto de escritorio",
    category: "setup",
    image: "https://m.media-amazon.com/images/I/41-h7XXl5SL._SS600_.jpg",
    tags: ["Tecnología"],
    search: "multicontacto escritorio 6 enchufes usb c",
    storeUrl: "https://www.amazon.com.mx/dp/B0BS72G3LY/",
    storeLabel: "Ver en Amazon",
  },
  {
    id: "multicontacto-clip-mesa",
    name: "Multicontacto AnnTane (clip de mesa)",
    category: "setup",
    image: "https://m.media-amazon.com/images/I/318CEcxN97L._SS600_.jpg",
    tags: ["Tecnología"],
    search: "multicontacto escritorio clip mesa AnnTane 40W",
    storeUrl: "https://www.amazon.com.mx/dp/B0F625CQM2/",
    storeLabel: "Ver en Amazon",
    priority: true,
  },
  {
    id: "mousepad-asus",
    name: "Mousepad Asus ROG Sheath XL",
    category: "setup",
    image: "https://m.media-amazon.com/images/I/414Y+Q2dTfL._SS600_.jpg",
    tags: ["Accesorios", "Computadoras"],
    search: "Asus ROG Sheath mousepad XL",
    storeUrl: "https://www.amazon.com.mx/dp/B01G5ATZAE/",
    storeLabel: "Ver en Amazon",
  },
  {
    id: "mouspad-excovip-xxl-planetas",
    name: "Mousepad Excovip XXL Planetas",
    category: "setup",
    image: "https://m.media-amazon.com/images/I/71EZuG4REfL._AC_SL1500_.jpg",
    tags: ["Accesorios", "Computadoras"],
    search: "Excovip XXL mousepad planetas",
    storeUrl: "https://a.co/d/3Vzlv5F",
    storeLabel: "Ver en Amazon",
  },
  {
    id: "mousepad-corsair",
    name: "Mousepad Corsair MM700 RGB",
    category: "setup",
    image: "https://m.media-amazon.com/images/I/21GzCLYWWeL._SS600_.jpg",
    tags: ["Accesorios", "Computadoras"],
    search: "Corsair MM700 RGB extended mouse pad",
    storeUrl:
      "https://www.corsair.com/lm/es/p/mousepads/ch-9417080-ww/mm700-rgb-extended-3xl-cloth-gaming-mouse-pad-desk-mat-ch-9417080-ww",
    storeLabel: "Ver en Corsair",
  },
  {
    id: "soporte-monitor-linkon",
    name: "Soporte para monitor Linkon",
    category: "setup",
    image: "https://ss637.liverpool.com.mx/xl/1175098409.jpg",
    tags: ["Tecnología", "Accesorios"],
    search: "Soporte para monitor de escritorio Linkon",
    storeUrl:
      "https://www.liverpool.com.mx/tienda/pdp/soporte-para-monitor-de-escritorio-linkon/99983759943",
    storeLabel: "Ver en Liverpool",
    priority: true,
  },
  {
    id: "soporte-movil-tv",
    name: "Soporte móvil para monitor / TV",
    category: "setup",
    image: "https://m.media-amazon.com/images/I/41r4JFl5QoL._SS600_.jpg",
    tags: ["Tecnología", "Accesorios"],
    search: "soporte móvil para tv 65 pulgadas altura ajustable",
    storeUrl: "https://www.amazon.com.mx/dp/B0DHZ6H7JL/",
    storeLabel: "Ver en Amazon",
  },
  {
    id: "xiaomi-monitor-lightbar",
    name: "Xiaomi Mi Computer Monitor Light Bar",
    category: "setup",
    image: "https://m.media-amazon.com/images/I/414OKh3xZlL.jpg",
    tags: ["Tecnología", "Accesorios"],
    search: "Xiaomi Mi Computer Monitor Light Bar",
    storeUrl:
      "https://www.mi.com/mx/product/mi-computer-monitor-light-bar/buy/",
    storeLabel: "Ver en Xiaomi",
    priority: true,
  },
  {
    id: "echo-dot",
    name: "Amazon Echo Dot (5ª gen)",
    category: "setup",
    image: "https://m.media-amazon.com/images/I/319ZaoJcE6L._AC_.jpg",
    tags: ["Tecnología"],
    search: "Amazon Echo Dot 5a generación",
    storeUrl: "https://www.amazon.com.mx/dp/B09B8V1LZ3/",
    storeLabel: "Ver en Amazon",
  },
  {
    id: "Luces-LED-TV-Retroiluminación-3-Lite-con-Fish-Eye-Función",
    name: "Luces LED TV Retroiluminación 3 Lite con Fish Eye Función",
    category: "setup",
    image: "https://m.media-amazon.com/images/I/71j1PNlJTxL._AC_SL1500_.jpg",
    tags: ["Decorativos", "Tecnología"],
    search: "Luces LED TV Retroiluminación 3 Lite con Fish Eye Función",
    storeUrl: "https://a.co/d/61ySk0G",
    storeLabel: "Ver en Amazon",
  },

  // === DÍA A DÍA / MOVILIDAD ===================================
  {
    id: "mochila-borealis",
    name: "Mochila The North Face Borealis",
    category: "daylife",
    image: "https://m.media-amazon.com/images/I/41VxXMEmszL._SS600_.jpg",
    tags: ["Mochilas", "Uso diario"],
    search: "Mochila The North Face Borealis laptop",
    storeUrl: "https://www.amazon.com.mx/dp/B0CN9S5SWD/",
    storeLabel: "Ver en Amazon",
  },
  {
    id: "portafolios-lubardy",
    name: "Portafolios Lubardy para laptop",
    category: "daylife",
    image: "https://m.media-amazon.com/images/I/71-ztHgv9YL._AC_SL1500_.jpg",
    tags: ["Mochilas", "Portafolios"],
    search: "Portafolios Lubardy 16 pulgadas laptop",
    storeUrl: "https://www.amazon.com.mx/dp/B0D83VR6GV/",
    storeLabel: "Ver en Amazon",
  },
  {
    id: "Portafolios-para-Hombre-15.6-Pulgadas-Piel-Maletin-Laptop-Bolsa-de-Mensajero-Impermeable-Vintage-Cuero",
    name: "Portafolios para Hombre 15.6 Pulgadas Piel Maletín Laptop Bolsa de Mensajero Impermeable Vintage Cuero",
    category: "daylife",
    image: "https://m.media-amazon.com/images/I/71-AED-AWSL._AC_SL1100_.jpg",
    tags: ["Mochilas", "Portafolios"],
    search:
      "Portafolios para Hombre 15.6 Pulgadas Piel Maletín Laptop Bolsa de Mensajero Impermeable Vintage Cuero",
    storeUrl: "https://a.co/d/hEj5viM",
    storeLabel: "Ver en Amazon",
  },
  {
    id: "Stanley-Botella-Clásica-al-Vacío",
    name: "Stanley Botella Clásica al Vacío",
    category: "daylife",
    image: "https://m.media-amazon.com/images/I/61hxLmqn7GL._AC_SL1500_.jpg",
    tags: ["Termos", "Uso diario"],
    search: "Stanley Botella Clásica al Vacío 532ml",
    storeUrl: "https://a.co/d/1DK1w2z",
    storeLabel: "Ver en Amazon",
  },
  {
    id: "Funda-de-FineWoven-con-MagSafe-para-iPhone-15",
    name: "Funda de FineWoven con MagSafe para iPhone 15",
    category: "daylife",
    image: "https://m.media-amazon.com/images/I/51UwFoiodtL._AC_SL1000_.jpg",
    tags: ["Accesorios", "Celular"],
    search: "Funda FineWoven MagSafe iPhone 15",
    storeUrl: "https://a.co/d/0Y6APRB",
    storeLabel: "Ver en Amazon",
  },
  {
    id: "Tommy-Hilfiger-Original-Stretch-Camisa-Hombre",
    name: "Tommy Hilfiger Original Stretch Camisa Hombre",
    category: "daylife",
    image: "https://m.media-amazon.com/images/I/61H0kh5cJGL._AC_SY879_.jpg",
    tags: ["Ropa", "Uso diario"],
    search: "Tommy Hilfiger Original Stretch Camisa Hombre",
    storeUrl: "https://a.co/d/8ZOywoQ",
    storeLabel: "Ver en Amazon",
  },
  {
    id: "Stanley-AeroLight-Botella-de-tránsito-de-20-onzas",
    name: "Stanley AeroLight - Botella de tránsito de 20 onzas",
    category: "daylife",
    image: "https://m.media-amazon.com/images/I/71tR8LNu4mL._AC_SL1500_.jpg",
    tags: ["Termos", "Uso diario"],
    search: "Stanley AeroLight Botella de tránsito de 20 onzas",
    storeUrl: "https://a.co/d/j2vpnQK",
    storeLabel: "Ver en Amazon",
  },
  // === BAJO ELÉCTRICO ==========================================
  {
    id: "fender-correa-piel",
    name: "Correa de piel Fender",
    category: "bass",
    image: "https://m.media-amazon.com/images/I/41IHjUTR-EL._SS600_.jpg",
    tags: ["Accesorios"],
    search: "Fender leather strap brown bass",
    storeUrl: "https://www.amazon.com.mx/dp/B000EELFI8/",
    storeLabel: "Ver en Amazon",
  },
  {
    id: "fender-correa-pana",
    name: "Correa Fender de pana",
    category: "bass",
    image: "https://m.media-amazon.com/images/I/41wZ5YnU9bL._SS600_.jpg",
    tags: ["Accesorios"],
    search: "Fender corduroy strap",
    storeUrl: "https://www.amazon.com.mx/dp/B0B9QN1H4G/",
    storeLabel: "Ver en Amazon",
  },
  {
    id: "fender-animal-print",
    name: "Correa Fender Animal Print",
    category: "bass",
    image: "https://m.media-amazon.com/images/I/41+GI4pTT4L._SS600_.jpg",
    tags: ["Accesorios"],
    search: "Fender animal print strap zebra",
    storeUrl: "https://www.amazon.com.mx/dp/B08CSXZDVP/",
    storeLabel: "Ver en Amazon",
  },
  {
    id: "levys-leather-wide",
    name: "Correa Levy's de piel ancha",
    category: "bass",
    image: "https://m.media-amazon.com/images/I/31gO1Lu+UCL._SS600_.jpg",
    tags: ["Accesorios"],
    search: "Levy's leather 3 inch bass strap",
    storeUrl: "https://www.amazon.com.mx/dp/B0845Q9BTT/",
    storeLabel: "Ver en Amazon",
  },

  // === PERFUMES ================================================
  {
    id: "polo-sport",
    name: "Ralph Lauren Polo Sport EDT",
    category: "perfumes",
    image: "https://ss701.liverpool.com.mx/xl/6783422.jpg",
    tags: ["Perfumes", "Uso diario"],
    search: "Ralph Lauren Polo Sport EDT 125ml",
    storeUrl: "https://www.amazon.com.mx/dp/B00EXW1PRS/",
    storeLabel: "Ver en Amazon",
    priority: true,
  },
  {
    id: "Armaf_odyssey_limoni",
    name: "Armaf Odyssey Limoni EDP",
    category: "perfumes",
    image: "https://m.media-amazon.com/images/I/61hLQ5ujH3L._AC_SL1500_.jpg",
    tags: ["Perfumes", "Uso diario"],
    search: "Armaf Odyssey Limoni EDP 100ml",
    storeUrl: "https://a.co/d/76SFjsK",
    storeLabel: "Ver en Amazon",
    priority: true,
  },
  {
    id: "Armaf_Odyssey_Dubai_Chocolat",
    name: "Armaf Odyssey Dubai Chocolat EDP",
    category: "perfumes",
    image: "https://m.media-amazon.com/images/I/7143opljnoL._AC_SL1500_.jpg",
    tags: ["Perfumes", "Uso ocasional"],
    search: "Armaf Odyssey Dubai Chocolat EDP 100ml",
    storeUrl: "https://a.co/d/2WleseG",
    storeLabel: "Ver en Amazon",
    priority: true,
  },
  {
    id: "Lacoste_L.12.12_Blanco",
    name: "Lacoste L.12.12 Blanc EDT",
    category: "perfumes",
    image: "https://m.media-amazon.com/images/I/71Pk21AjqWL._AC_SL1500_.jpg",
    tags: ["Perfumes", "Uso diario"],
    search: "Lacoste L.12.12 Blanc EDT 100ml",
    storeUrl: "https://a.co/d/37zJw0Q",
    storeLabel: "Ver en Amazon",
  },
  {
    id: "Moschino_Toy_Boy_Edp",
    name: "Moschino Toy Boy EDP",
    category: "perfumes",
    image: "https://m.media-amazon.com/images/I/510i5dxTWoL._AC_SL1000_.jpg",
    tags: ["Perfumes", "Uso ocasional"],
    search: "Moschino Toy Boy EDP 100ml",
    storeUrl: "https://a.co/d/ePQstfs",
    storeLabel: "Ver en Amazon",
  },
  {
    id: "Hugo_by_Hugo_Boss",
    name: "Hugo by Hugo Boss EDT",
    category: "perfumes",
    image: "https://m.media-amazon.com/images/I/71n7lCqrv-L._AC_SL1500_.jpg",
    tags: ["Perfumes", "Uso diario"],
    search: "Hugo by Hugo Boss EDT 125ml",
    storeUrl: "https://a.co/d/5GWKtRw",
    storeLabel: "Ver en Amazon",
  },

  // === ENTRETENIMIENTO =========================================
  {
    id: "lego-jazz-quartet",
    name: "LEGO Ideas Jazz Quartet 21334",
    category: "fun",
    image:
      "https://www.lego.com/cdn/cs/set/assets/blt626a07dcab0e99bd/21334_alt1.png?format=webply&fit=bounds&quality=60&width=800&height=800&dpr=2",
    tags: ["Decorativos"],
    search: "LEGO Ideas Jazz Quartet 21334",
    storeUrl: "https://www.lego.com/es-mx/product/jazz-quartet-21334",
    storeLabel: "Ver en LEGO",
  },
  {
    id: "bbng-vinyl-lll",
    name: "Vinilo BadBadNotGood III",
    category: "fun",
    image: "https://m.media-amazon.com/images/I/618sBBU7vTL._AC_SL1500_.jpg",
    tags: ["Musica", "Decorativos"],
    search: "BadBadNotGood III vinyl",
    storeUrl: "https://a.co/d/gkhZTeb",
    storeLabel: "Ver en Amazon",
  },
  {
    id: "MF-doom-mm-food-vinyl",
    name: "Vinilo MF DOOM - Mm..Food",
    category: "fun",
    image: "https://m.media-amazon.com/images/I/81yLIHzNaDL._AC_SL1500_.jpg",
    tags: ["Musica", "Decorativos"],
    search: "MF DOOM Mm..Food vinyl",
    storeUrl: "https://a.co/d/cI6VYac",
    storeLabel: "Ver en Amazon",
  },
  {
    id: "bbng-vinyl-iv",
    name: "Vinilo BadBadNotGood IV",
    category: "fun",
    image: "https://m.media-amazon.com/images/I/719qN5IueZL._AC_SL1500_.jpg",
    tags: ["Musica", "Decorativos"],
    search: "BadBadNotGood IV vinyl",
    storeUrl: "https://a.co/d/8Z9Jfz5",
    storeLabel: "Ver en Amazon",
  },
  {
    id: "Vinilo_BadBadNotGood_Mid_Spiral",
    name: "Vinilo BadBadNotGood Mid Spiral",
    category: "fun",
    image: "https://m.media-amazon.com/images/I/61ERxKlDBSL._AC_SL1200_.jpg",
    tags: ["Musica", "Decorativos"],
    search: "BadBadNotGood Mid Spiral vinyl",
    storeUrl: "https://a.co/d/h5tp8nG",
    storeLabel: "Ver en Amazon",
    purchased: true,
    priority: true,
  },
  {
    id: "Spider-Man_Kravens_Last_Hunt_New_Printing",
    name: "Spider-Man: Kraven's Last Hunt (New Printing)",
    category: "fun",
    image: "https://m.media-amazon.com/images/I/813NhXAicML._SL1500_.jpg",
    tags: ["Libros", "Coleccionables"],
    search: "Spider-Man Kraven's Last Hunt New Printing",
    storeUrl:
      "https://www.amazon.com.mx/dp/0785134506/?coliid=I3AF33JNNSOV45&colid=3AY48F4EYMKCM&psc=1&ref_=cm_sw_r_cp_ud_lstpd_P3VXW30R724KHRXBNCEM",
    storeLabel: "Ver en Amazon",
  },
  {
    id: "Spiderman-La-Ultima-Caceria-De-Kraven-Must-Have",
    name: "Spiderman: La Última Cacería De Kraven (Must Have)",
    category: "fun",
    image: "https://m.media-amazon.com/images/I/71S0KCaGDEL._SL1500_.jpg",
    tags: ["Libros", "Coleccionables"],
    search: "Spiderman La Última Cacería De Kraven Must Have",
    storeUrl:
      "https://www.amazon.com.mx/dp/8411016374/?coliid=IN94KTXA9PX6T&colid=3AY48F4EYMKCM&psc=1&ref_=cm_sw_r_cp_ud_lstpd_P3VXW30R724KHRXBNCEM_4",
    storeLabel: "Ver en Amazon",
  },
  {
    id: "Spiderman-PPoster-de-pelicula-De-vaiven-Tamano-68-58-cm-x-101-6-cm",
    name: "Spiderman Póster de película De vaivén Tamaño 68.58 cm x 101.6 cm",
    category: "fun",
    image: "https://m.media-amazon.com/images/I/61FqGnjiXDL._AC_SL1000_.jpg",
    tags: ["Posters", "Decorativos"],
    search: "Spiderman Póster de película De vaivén Tamaño 68.58 cm x 101.6 cm",
    storeUrl: "https://a.co/d/aItGVcW",
    storeLabel: "Ver en Amazon",
  },
  {
    id: "Paladone-Marvel-Avengers-Logo-Light-Placa-decorativa-con-2-modos-de-iluminación",
    name: "Paladone Marvel Avengers Logo Light Placa decorativa con 2 modos de iluminación",
    category: "fun",
    image: "https://m.media-amazon.com/images/I/810EQR6qKsL._AC_SL1500_.jpg",
    tags: ["Decorativos"],
    search:
      "Paladone Marvel Avengers Logo Light Placa decorativa con 2 modos de iluminación",
    storeUrl: "https://a.co/d/1Vo4QJY",
    storeLabel: "Ver en Amazon",
  },
  {
    id: "Marvel-80-Años-Spiderman-Póster",
    name: "Marvel 80 Años Spiderman Póster",
    category: "fun",
    image: "https://m.media-amazon.com/images/I/61YQcuXN1oL._AC_SL1000_.jpg",
    tags: ["Posters", "Decorativos"],
    search: "Marvel 80 Años Spiderman Póster",
    storeUrl: "https://a.co/d/bmrcytl",
    storeLabel: "Ver en Amazon",
  },

  // === SNACKS (ejemplo genérico) ===============================
  {
    id: "Surtido_Turrones_Ean_200_Grs",
    name: "Surtido Turrones Ean 200 Grs",
    category: "snacks",
    image: "https://m.media-amazon.com/images/I/71sLyKCcLcL._AC_SL1500_.jpg",
    tags: ["Alimentos", "Dulces"],
    search: "Surtido Turrones Ean 200 Grs",
    storeUrl: "https://a.co/d/acViYbG",
    storeLabel: "Ver en Amazon",
  },
  {
    id: "Turin_Masterpieces_Chocolates_rellenos_de_Ganache_Estuche_120_g",
    name: "Turin Masterpieces Chocolates rellenos de Ganache Estuche 120 g",
    category: "snacks",
    image: "https://m.media-amazon.com/images/I/71jb5OSdBLL._AC_SL1500_.jpg",
    tags: ["Chocolates", "Dulces", "Alimentos"],
    search: "Turin Masterpieces Chocolates rellenos de Ganache Estuche 120g",
    storeUrl: "https://a.co/d/7Zxw4yg",
    storeLabel: "Ver en Amazon",
  },
  {
    id: "Turin_Baileys_Original_Chocolates_con_leche_y_licor_Tubo_180g",
    name: "Turin Baileys Original Chocolates con leche y licor Tubo 180g",
    category: "snacks",
    image: "https://m.media-amazon.com/images/I/61NrR2h5WdL._AC_SL1500_.jpg",
    tags: ["Chocolates", "Dulces", "Alimentos"],
    search: "Turin Baileys Original Chocolates con leche y licor Tubo 180g",
    storeUrl: "https://a.co/d/hTBVtea",
    storeLabel: "Ver en Amazon",
  },
  {
    id: "Gamesa_Florentinas_Sabor_Cajeta_Galletas_332g",
    name: "Gamesa Florentinas Sabor Cajeta Galletas 332g",
    category: "snacks",
    image: "https://m.media-amazon.com/images/I/61imuzGc+TL._AC_SL1001_.jpg",
    tags: ["Alimentos", "Dulces"],
    search: "Gamesa Florentinas Sabor Cajeta Galletas 332g",
    storeUrl: "https://a.co/d/grRil78",
    storeLabel: "Ver en Amazon",
  },
  {
    id: "Oyereli_Chocolate_Artesanal_Prémium_Especialidad_Avellanas_150gr",
    name: "Oyereli Chocolate Artesanal Prémium Especialidad Avellanas 150gr",
    category: "snacks",
    image: "https://m.media-amazon.com/images/I/61POpSONw7L._AC_SL1500_.jpg",
    tags: ["Chocolates", "Dulces", "Alimentos"],
    search: "Oyereli Chocolate Artesanal Prémium Especialidad Avellanas 150gr",
    storeUrl: "https://a.co/d/aGEwf2c",
    storeLabel: "Ver en Amazon",
  },

  // === Otras categorias ===

  {
    id: "Pococo_Proyector_de_estrellas",
    name: "Pococo Proyector de estrellas",
    category: "all",
    image: "https://m.media-amazon.com/images/I/71qT0Tg0xDL._AC_SL1500_.jpg",
    tags: ["Decorativos"],
    search: "Pococo Proyector de estrellas",
    storeUrl: "https://a.co/d/8Tbm0ZE",
    storeLabel: "Ver en Amazon",
  },
  {
    id: "Synecdoche-New York-[Blu-ray]-[Importado]",
    name: "Synecdoche New York [Blu-ray] [Importado]",
    category: "all",
    image: "https://m.media-amazon.com/images/I/91vclTLueyL._AC_SL1500_.jpg",
    tags: ["Peliculas"],
    search: "Synecdoche New York Blu-ray",
    storeUrl: "https://a.co/d/hYAtJ4D",
    storeLabel: "Ver en Amazon",
  },
  {
    id: "Control-inalámbrico-Electric-Volt-para-Xbox Series-X|S",
    name: "Control inalámbrico Electric Volt para Xbox Series X|S",
    category: "all",
    image: "https://m.media-amazon.com/images/I/51hFzk7eKTL._AC_SL1000_.jpg",
    tags: ["Tecnología", "Videojuegos"],
    search: "Control inalámbrico para Xbox Series X|S",
    storeUrl: "https://a.co/d/dbZGAwd",
    storeLabel: "Ver en Amazon",
  },
  {
    id: "Amazon-fire-tv-stick-4k-max",
    name: "Amazon Fire TV Stick 4K Max",
    category: "all",
    image: "https://m.media-amazon.com/images/I/71B0drJ9K2L._AC_SL1500_.jpg",
    tags: ["Tecnología"],
    search: "Amazon Fire TV Stick 4K Max",
    storeUrl: "https://a.co/d/gcBLt7V",
    storeLabel: "Ver en Amazon",
  },
  {
    id: "Sony-PS-LX310BT-Tocadiscos-con-conectividad-Bluetooth",
    name: "Sony PS-LX310BT Tocadiscos con conectividad Bluetooth",
    category: "all",
    image: "https://m.media-amazon.com/images/I/51+Xja4sTxL._AC_SL1000_.jpg",
    tags: ["Musica", "Tecnología"],
    search: "Sony PS-LX310BT Tocadiscos con conectividad Bluetooth",
    storeUrl: "https://a.co/d/5F9Zp0l",
    storeLabel: "Ver en Amazon",
  },
  {
    id: "Oster-Freidora de Aire Digital-Recubrimiento-Oster-DiamondForce",
    name: "Oster Freidora de Aire Digital Recubrimiento Oster DiamondForce",
    category: "all",
    image: "https://m.media-amazon.com/images/I/711RXjtIXwL._AC_SL1500_.jpg",
    tags: ["Otros", "Cocina"],
    search: "Oster Freidora de Aire Digital Recubrimiento Oster DiamondForce",
    storeUrl: "https://a.co/d/0Q50bs6",
    storeLabel: "Ver en Amazon",
  },
  {
    id: "MAGMALIFE-Maleta-de-Viaje-10-kg-Celestial-Carry-On",
    name: "MAGMALIFE Maleta de Viaje 10 kg Celestial Carry-On",
    category: "all",
    image: "https://m.media-amazon.com/images/I/61nEZy1GXKL._AC_SX679_.jpg",
    tags: ["Viajes", "Mochilas"],
    search: "MAGMALIFE Maleta de Viaje 10 kg Celestial Carry-On",
    storeUrl: "https://a.co/d/eRC5v2e",
    storeLabel: "Ver en Amazon",
    priority: true,
  },
  {
    id: "Maleta-BAGIAU-de-Viaje-20-Carry-On-Rígida-Equipaje-de-Mano-Cabina-con-8-ruedas-y-candado-integrado",
    name: 'Maleta BAGIAU de Viaje 20" Carry On Rígida, Equipaje de Mano Cabina con 8 ruedas y candado integrado',
    category: "all",
    image: "https://m.media-amazon.com/images/I/61phpfztkUL._AC_SX679_.jpg",
    tags: ["Viajes", "Mochilas"],
    search:
      "Maleta BAGIAU de Viaje 20 Carry On Rígida Equipaje de Mano Cabina con 8 ruedas y candado integrado",
    storeUrl: "https://a.co/d/0GGQ0eW",
    storeLabel: "Ver en Amazon",
    priority: true,
  },
  {
    id: "Amazon-Basics-Equipaje-de-mano-rígido-de-53.3cm",
    name: "Amazon Basics Equipaje de mano rígido de 53.3cm",
    category: "all",
    image: "https://m.media-amazon.com/images/I/91g9s0UqTBL._AC_SL1500_.jpg",
    tags: ["Viajes", "Mochilas"],
    search: "Amazon Basics Equipaje de mano rígido de 53.3cm",
    storeUrl: "https://a.co/d/6iSLtqC",
    storeLabel: "Ver en Amazon",
    priority: true,
  },
  {
    id: "El-aire-del-desierto-marroqui",
    name: "El aire del desierto marroquí",
    category: "perfumes",
    image: "https://tauerperfumes.com.mx/wp-content/uploads/2020/07/001.jpg",
    tags: ["Perfumes"],
    search: "Tauer Perfumes El aire del desierto marroquí",
    storeUrl: "https://tauerperfumes.com.mx/?product=lair-du-desert-marcoain",
    storeLabel: "Ver en Tauer",
    priority: true, 
  },
];

window.CATEGORY_CONTAINER_IDS = {
  setup: "cards-setup",
  daylife: "cards-daylife",
  bass: "cards-bass",
  perfumes: "cards-perfumes",
  fun: "cards-fun",
  snacks: "cards-snacks",
  all: "cards-all",
  premium: "cards-premium",
};